version: '3.5'

services:
  interactive-video-web:
    build:
      dockerfile: Dockerfile
      context: ./interactive-video-web
    image: thalfm/interactive-video-web
    container_name: interactive-video-web
    volumes:
      - ./interactive-video-web/web:/opt/web
      - ./interactive-video-web/nginx/default:/etc/nginx/sites-available/default
    ports:
      - 8001:80
      - 3000:3000
    networks:
      - interactive-video

  interactive-video-catalog-web:
    build:
      dockerfile: Dockerfile
      context: ./interactive-video-catalog-web
    image: thalfm/interactive-video-catalog-web
    container_name: interactive-video-catalog-web
    volumes:
      - ./interactive-video-catalog-web/web:/opt/web
      - ./interactive-video-catalog-web/nginx/default:/etc/nginx/sites-available/default
    ports:
      - 8002:80
      - 3001:3000
    networks:
      - interactive-video

  interactive-video-api:
    build:
      dockerfile: Dockerfile
      context: ./interactive-video-api
      args:
        - WITH_XDEBUG=true
    image: thalfm/interactive-video-api
    container_name: interactive-video-api
    volumes:
      - ./interactive-video-api/api:/opt/api
      - ./interactive-video-api/nginx/default:/etc/nginx/sites-available/default
      - ./interactive-video-api/php/overrides.ini:/etc/php/8.0/fpm/conf.d/overrides.ini
    ports:
      - 8000:80
    networks:
      - interactive-video
    env_file:
      - .env

  interactive-upload-socket:
    build:
      dockerfile: Dockerfile
      context: ./interactive-upload-socket
      target: development
    image: thalfm/interactive-upload-socket
    container_name: interactive-upload-socket
    volumes:
      - ./interactive-upload-socket:/home/node/app
      - /home/node/app/node_modules
    env_file:
      - ./interactive-upload-socket/.env
    ports:
    - 3003:3003
    entrypoint: nodemon -L
    networks:
      - interactive-video

  interactive-video-pgsql:
    image: postgres:13.1
    container_name: interactive-video-pgsql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=interactive
      - PGDATA=/temp/data
    volumes:
      - .database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - interactive-video

  interactive-video-rabbitmq:
    image: 'rabbitmq:3.8-management-alpine'
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - '.rabbitmq:/var/lib/rabbitmq/mnesia'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - interactive-video

  interactive-video-catalog-api:
    build:
      dockerfile: Dockerfile
      context: ./interactive-video-catalog-api
      target: development
    image: thalfm/interactive-video-catalog-api
    container_name: interactive-video-catalog-api
    volumes:
      - ./interactive-video-catalog-api:/home/node/app
      - /usr/src/app/node_modules
    environment:
      - HOST=0.0.0.0
    ports:
      - 3004:3000
    entrypoint: nodemon -L
    networks:
      - interactive-video

  interactive-video-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: interactive-video-elasticsearch
    environment:
      - discovery.type=single-node
      - node.name=interactive-video-elasticsearch
    volumes:
      - ./.elasticdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - interactive-video

  interactive-video-kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    container_name: interactive-video-kibana
    environment:
      ELASTICSEARCH_URL: http://interactive-video-elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://interactive-video-elasticsearch:9200"]'
    ports:
      - 5601:5601
    networks:
      - interactive-video

networks:
  interactive-video:
    driver: bridge
